project_id = "oqyehjqduvnrvuckzqer"

[functions.daily-cron]
verify_jwt = false

[functions.waha-session]
verify_jwt = false

[functions.waha-webhook]
verify_jwt = false

[functions.rest-api]
verify_jwt = false